exports.CASH_PAYMENT_TYPE = 'Cash';
exports.CASHBACK_PAYMENT_TYPE = 'CashBack';
exports.SSL_COMMERZ_PAYMENT_TYPE = 'SSLCommerce';
exports.BKASH_PAYMENT_TYPE = 'bKash';
exports.NAGAD_PAYMENT_TYPE = 'Nagad';
exports.OFFLINE_PAYMENT_TYPE = 'OfflinePay';

exports.REGULAR_ORDER_TYPE = 1;
exports.PARTIAL_ORDER_TYPE = 2;

exports.ORDER_REFUNDED_STATUS = 1;
exports.ORDER_NOT_REFUNDED_STATUS = 0;

exports.PAYMENT_STATUS_UNPAID = 1;
exports.PAYMENT_STATUS_PARTIALLY_PAID = 2;
exports.PAYMENT_STATUS_PAID = 3;
exports.PAYMENT_STATUS_NA = 4;

exports.PAYMENT_TRAN_TYPE_PAY = 1;
exports.PAYMENT_TRAN_TYPE_REFUND = 2;

exports.CANCELED_ORDER = 12;

exports.BANK_TRANSFER_OFFLINE_PAYMENT = 'bankTransfer';
exports.CASH_IN_ADVANCE_OFFLINE_PAYMENT = 'cashInAdvance';
exports.BANK_DEPOSIT_OFFLINE_PAYMENT = 'bankDeposit';
exports.MOBILE_TRANSFER_OFFLINE_PAYMENT = 'mobileTransfer';

exports.PENDING_PAYMENT_APPROVAL_STATUS = 1;
exports.APPROVED_PAYMENT_APPROVAL_STATUS = 2;
exports.REJECTED_PAYMENT_APPROVAL_STATUS = 3;
