exports.CASH_PAYMENT_TYPE = 'Cash';
exports.CASHBACK_PAYMENT_TYPE = 'CashBack';
exports.SSL_COMMERZ_PAYMENT_TYPE = 'SSLCommerce';
exports.BKASH_PAYMENT_TYPE = 'bKash';
exports.NAGAD_PAYMENT_TYPE = 'Nagad';

exports.REGULAR_ORDER_TYPE = 1;
exports.PARTIAL_ORDER_TYPE = 2;

exports.ORDER_REFUNDED_STATUS = 1;
exports.ORDER_NOT_REFUNDED_STATUS = 0;

exports.PAYMENT_STATUS_UNPAID = 1;
exports.PAYMENT_STATUS_PARTIALLY_PAID = 2;
exports.PAYMENT_STATUS_PAID = 3;
exports.PAYMENT_STATUS_NA = 4;
