/** Payment constants */
exports.CASH_PAYMENT_TYPE = 'Cash';
exports.CASHBACK_PAYMENT_TYPE = 'CashBack';
exports.SSL_COMMERZ_PAYMENT_TYPE = 'SSLCommerce';
exports.BKASH_PAYMENT_TYPE = 'bKash';
exports.NAGAD_PAYMENT_TYPE = 'Nagad';
exports.OFFLINE_PAYMENT_TYPE = 'OfflinePay';

exports.BANK_TRANSFER_OFFLINE_PAYMENT = 'bankTransfer';
exports.CASH_IN_ADVANCE_OFFLINE_PAYMENT = 'cashInAdvance';
exports.BANK_DEPOSIT_OFFLINE_PAYMENT = 'bankDeposit';
exports.MOBILE_TRANSFER_OFFLINE_PAYMENT = 'mobileTransfer';

exports.PENDING_PAYMENT_APPROVAL_STATUS = 1;
exports.APPROVED_PAYMENT_APPROVAL_STATUS = 2;
exports.REJECTED_PAYMENT_APPROVAL_STATUS = 3;

exports.PAYMENT_TRAN_TYPE_PAY = 1;
exports.PAYMENT_TRAN_TYPE_REFUND = 2;

/** Order constants */
exports.REGULAR_ORDER_TYPE = 1;
exports.PARTIAL_ORDER_TYPE = 2;

exports.PAYMENT_STATUS_UNPAID = 1;
exports.PAYMENT_STATUS_PARTIALLY_PAID = 2;
exports.PAYMENT_STATUS_PAID = 3;
exports.PAYMENT_STATUS_NA = 4;

exports.PENDING_SOME_OFFLINE_PAYMENTS_APPROVAL_STATUS = 1;
exports.CONFIRMED_ALL_OFFLINE_PAYMENTS_APPROVAL_STATUS = 2;
exports.NOT_APPLICABLE_OFFLINE_PAYMENTS_APPROVAL_STATUS = 3;

exports.ORDER_REFUNDED_STATUS = 1;
exports.ORDER_NOT_REFUNDED_STATUS = 0;

exports.CANCELED_ORDER = 12;

/** Product constants */
exports.PENDING_PRODUCT_APPROVAL_STATUS = 1;
exports.APPROVED_PRODUCT_APPROVAL_STATUS = 2;
exports.REJECTED_PRODUCT_APPROVAL_STATUS = 99;

/** User Roll Management Constants */
exports.ADMIN_USER_GROUP_NAME = 'admin';
exports.CUSTOMER_USER_GROUP_NAME = 'customer';
exports.SUPPLIER_USER_GROUP_NAME = 'supplier';
exports.OWNER_USER_GROUP_NAME = 'owner';

/** Warehouse constants */
exports.PENDING_WAREHOUSE_STATUS = 0;
exports.PROCESSING_WAREHOUSE_STATUS = 1;
exports.ACTIVE_WAREHOUSE_STATUS = 2;
exports.INACTIVE_WAREHOUSE_STATUS = 3;

/** Offer constants */
exports.REGULAR_OFFER_TYPE = 1;
exports.ANONDER_JHOR_OFFER_TYPE = 2;

exports.CATEGORY_WISE_OFFER_SELECTION_TYPE = 'Category wise';
exports.BRAND_WISE_OFFER_SELECTION_TYPE = 'Brand wise';
exports.VENDOR_WISE_OFFER_SELECTION_TYPE = 'Vendor wise';
exports.PRODUCT_WISE_OFFER_SELECTION_TYPE = 'Product wise';
exports.INDIVIDUAL_PRODUCT_WISE_OFFER_SELECTION_TYPE = 'individual_product';
