exports.anonderJhorRoute = {
  'GET /api/v1/anonderJhor/getAnonderJhor': 'AnonderJhorController.getAnonderJhor',
  'POST /api/v1/anonderJhor/jhorActiveStatusChange': 'AnonderJhorController.jhorActiveStatusChange',
  'POST /api/v1/anonderJhor/offerActiveStatusChange': 'AnonderJhorController.offerActiveStatusChange',
  'POST /api/v1/anonderJhor/offerForceStop': 'AnonderJhorController.offerForceStop',
  'POST /api/v1/anonderJhor/updateAnonderJhor': 'AnonderJhorController.updateAnonderJhor',
  'GET /api/v1/anonderJhor/getAllAnonderJhorOffersData': 'AnonderJhorController.getAllAnonderJhorOffersData',
  'GET /api/v1/anonderJhor/getAllCategories': 'AnonderJhorController.getAllCategories',
  'GET /api/v1/anonderJhor/getAllSubCategories': 'AnonderJhorController.getAllSubCategories',
  'GET /api/v1/anonderJhor/getAllSubSubCategories': 'AnonderJhorController.getAllSubSubCategories',
  'GET /api/v1/anonderJhor/getAnonderJhorOfferById': 'AnonderJhorController.getAnonderJhorOfferById',
  'POST /api/v1/anonderJhor/deleteAnonderJhorOffer': 'AnonderJhorController.deleteAnonderJhorOffer',
  'POST /api/v1/anonderJhor/anonderJhorOfferInsert': 'AnonderJhorController.anonderJhorOfferInsert',
  'POST /api/v1/anonderJhor/updateAnonderJhorOffer': 'AnonderJhorController.updateAnonderJhorOffer',
  'GET /api/v1/anonderJhor/getAnonderJhorAndOffers': 'AnonderJhorController.getAnonderJhorAndOffers',
  'GET /api/v1/anonderJhor/getWebAnonderJhorOfferById': 'AnonderJhorController.getWebAnonderJhorOfferById',
  'GET /api/v1/anonderJhor/generateOfferExcelById': 'AnonderJhorController.generateOfferExcelById',
  'GET /api/v1/anonderJhor/getAnonderJhorInfo': 'AnonderJhorController.getAnonderJhorInfo',
  'GET /api/v1/anonderJhor/generateJhorOfferedExcel': 'AnonderJhorController.generateJhorOfferedExcel',

};
